#!/usr/bin/env bash
# packer/thehive/scripts/install-thehive.sh — TheHive 5 Community via
# StrangeBee's official prod1-thehive Docker Compose profile.
#
# Steps:
#   1. Install Docker Engine + Compose plugin (official Docker repo).
#   2. Apply the kernel/sysctl tunings Elasticsearch needs.
#   3. Clone StrangeBeeCorp/docker at the pinned ref and select the
#      prod1-thehive profile.
#   4. Override versions.env with the pinned image tags so the build
#      pulls deterministic images, then run their init.sh which
#      generates self-signed certs, secret.conf, and the .env file.
#   5. Cap each JVM heap at the lab budget (1G default) — StrangeBee's
#      defaults assume a 16 GB host.
#   6. Pre-pull every image so first vagrant up boots fast.
#   7. Install a systemd unit that brings the stack up at boot.
#   8. Stage data dir + nginx port for the lab IP.

set -euo pipefail

REF="${SOCOOL_STRANGEBEE_DOCKER_REF:?upstream ref required}"
THEHIVE_VER="${SOCOOL_THEHIVE_IMAGE_VERSION:?thehive image version required}"
CASS_VER="${SOCOOL_CASSANDRA_IMAGE_VERSION:?cassandra image version required}"
ES_VER="${SOCOOL_ELASTICSEARCH_IMAGE_VERSION:?elasticsearch image version required}"
NGINX_VER="${SOCOOL_NGINX_IMAGE_VERSION:?nginx image version required}"
CASS_HEAP="${SOCOOL_CASSANDRA_HEAP_MB:?cassandra heap required}"
ES_HEAP="${SOCOOL_ELASTICSEARCH_HEAP_MB:?elasticsearch heap required}"
TH_HEAP="${SOCOOL_THEHIVE_HEAP_MB:?thehive heap required}"

THEHIVE_DIR=/opt/thehive
SRC_DIR=/opt/strangebee-docker

# ─── 1. Docker Engine (Debian/Ubuntu official repo) ─────────────────────
echo "[install-thehive] installing Docker..."
apt-get update
apt-get install -y ca-certificates curl gnupg git jq
install -d -m 0755 /etc/apt/keyrings
curl -fsSL --proto '=https' --tlsv1.2 \
    https://download.docker.com/linux/ubuntu/gpg \
    | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
chmod a+r /etc/apt/keyrings/docker.gpg
arch="$(dpkg --print-architecture)"
codename="$(. /etc/os-release && echo "$VERSION_CODENAME")"
printf 'deb [arch=%s signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu %s stable\n' \
    "$arch" "$codename" > /etc/apt/sources.list.d/docker.list
apt-get update
apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
systemctl enable docker
systemctl start docker

# ─── 2. Elasticsearch / OpenSearch sysctl tuning ────────────────────────
# Production-mode ES requires vm.max_map_count >= 262144 or it refuses
# to start. Apply now AND persist.
echo "[install-thehive] applying vm.max_map_count tuning..."
echo 'vm.max_map_count=262144' > /etc/sysctl.d/99-thehive.conf
sysctl --system >/dev/null

# ─── 3. Clone StrangeBee Compose profile at pinned ref ──────────────────
echo "[install-thehive] cloning StrangeBeeCorp/docker @ ${REF}..."
rm -rf "$SRC_DIR"
git clone --depth=1 --branch "$REF" \
    https://github.com/StrangeBeeCorp/docker.git "$SRC_DIR"

install -d -m 0755 "$THEHIVE_DIR"
cp -a "$SRC_DIR/prod1-thehive/." "$THEHIVE_DIR/"

# ─── 4. Pin image versions ──────────────────────────────────────────────
# StrangeBee's compose reads versions.env via --env-file; we write our
# own pinned copy alongside the profile so docker compose can be run
# from THEHIVE_DIR without referencing the upstream clone.
echo "[install-thehive] pinning image versions..."
cat > "$THEHIVE_DIR/versions.env" <<EOF
# Generated by packer/thehive/scripts/install-thehive.sh — pinned for
# reproducibility. Bump variables.pkr.hcl + rebuild to update.
cassandra_image_version=${CASS_VER}
elasticsearch_image_version=${ES_VER}
thehive_image_version=${THEHIVE_VER}
nginx_image_version=${NGINX_VER}
EOF

# ─── 5. Run StrangeBee's init.sh (generates certs, secret.conf, .env) ───
# The init script is interactive by default but accepts a server name
# via env. We pass the lab IP so the self-signed cert's CN matches
# how analysts will reach the UI.
echo "[install-thehive] running StrangeBee init.sh..."
cd "$THEHIVE_DIR"
chmod +x ./scripts/*.sh
SERVER_NAME='thehive.socool.lab' bash ./scripts/init.sh </dev/null || {
    echo "[install-thehive] init.sh exited non-zero; falling back to manual stub generation"
    # Minimum viable fallback so the stack still starts. The runbook
    # tells the operator to re-run init.sh by hand if certs are wrong.
    install -d -m 0700 ./thehive/config ./certificates
    : > ./thehive/config/secret.conf
    : > ./thehive/config/index.conf
}

# ─── 6. Cap JVM heaps to lab budget ─────────────────────────────────────
# Patch versions of the per-component env into the .env file
# generated by init.sh. We append; later definitions win in compose.
echo "[install-thehive] capping JVM heaps (cassandra=${CASS_HEAP}M es=${ES_HEAP}M thehive=${TH_HEAP}M)..."
{
    echo ""
    echo "# SOCool — heap caps to fit the lab's 8 GB VM budget."
    echo "MAX_HEAP_SIZE=${CASS_HEAP}M"
    echo "HEAP_NEWSIZE=$((CASS_HEAP / 4))M"
    echo "ES_JAVA_OPTS=-Xms${ES_HEAP}m -Xmx${ES_HEAP}m"
    echo "JVM_OPTS=-Xms${TH_HEAP}m -Xmx${TH_HEAP}m"
} >> "$THEHIVE_DIR/.env"

# ─── 7. Pre-pull images ─────────────────────────────────────────────────
# Brings the whole stack on-disk before vagrant up so the first lab
# boot doesn't need a 2 GB download over NAT.
echo "[install-thehive] pre-pulling images (this is ~2 GB)..."
( cd "$THEHIVE_DIR" && docker compose --env-file versions.env --env-file .env pull --ignore-pull-failures )

# ─── 8. Systemd unit — bring the stack up at boot ───────────────────────
cat > /etc/systemd/system/socool-thehive.service <<EOF
[Unit]
Description=SOCool TheHive 5 Community (Docker Compose stack)
After=docker.service network-online.target
Requires=docker.service

[Service]
Type=oneshot
RemainAfterExit=yes
WorkingDirectory=${THEHIVE_DIR}
ExecStart=/usr/bin/docker compose --env-file versions.env --env-file .env up -d
ExecStop=/usr/bin/docker compose --env-file versions.env --env-file .env down

[Install]
WantedBy=multi-user.target
EOF
systemctl enable socool-thehive.service

echo "[install-thehive] done."
